.class public final Lorg/apache/poi/hssf/record/chart/TextRecord;
.super Lorg/apache/poi/hssf/record/StandardRecord;
.source "TextRecord.java"


# static fields
.field public static final DATA_LABEL_PLACEMENT_ABOVE:S = 0x5s

.field public static final DATA_LABEL_PLACEMENT_AUTO:S = 0x9s

.field public static final DATA_LABEL_PLACEMENT_AXIS:S = 0x4s

.field public static final DATA_LABEL_PLACEMENT_BELOW:S = 0x6s

.field public static final DATA_LABEL_PLACEMENT_CENTER:S = 0x3s

.field public static final DATA_LABEL_PLACEMENT_CHART_DEPENDENT:S = 0x0s

.field public static final DATA_LABEL_PLACEMENT_INSIDE:S = 0x2s

.field public static final DATA_LABEL_PLACEMENT_LEFT:S = 0x7s

.field public static final DATA_LABEL_PLACEMENT_OUTSIDE:S = 0x1s

.field public static final DATA_LABEL_PLACEMENT_RIGHT:S = 0x8s

.field public static final DATA_LABEL_PLACEMENT_USER_MOVED:S = 0xas

.field public static final DISPLAY_MODE_OPAQUE:S = 0x2s

.field public static final DISPLAY_MODE_TRANSPARENT:S = 0x1s

.field public static final HORIZONTAL_ALIGNMENT_BOTTOM:B = 0x3t

.field public static final HORIZONTAL_ALIGNMENT_CENTER:B = 0x2t

.field public static final HORIZONTAL_ALIGNMENT_JUSTIFY:B = 0x4t

.field public static final HORIZONTAL_ALIGNMENT_LEFT:B = 0x1t

.field public static final ROTATION_NONE:S = 0x0s

.field public static final ROTATION_ROTATED_90_DEGREES:S = 0x2s

.field public static final ROTATION_ROTATED_90_DEGREES_CLOCKWISE:S = 0x3s

.field public static final ROTATION_TOP_TO_BOTTOM:S = 0x1s

.field public static final VERTICAL_ALIGNMENT_BOTTOM:B = 0x3t

.field public static final VERTICAL_ALIGNMENT_CENTER:B = 0x2t

.field public static final VERTICAL_ALIGNMENT_JUSTIFY:B = 0x4t

.field public static final VERTICAL_ALIGNMENT_TOP:B = 0x1t

.field private static final autoBackground:Lorg/apache/poi/util/BitField;

.field private static final autoColor:Lorg/apache/poi/util/BitField;

.field private static final autoGeneratedText:Lorg/apache/poi/util/BitField;

.field private static final autoLabelDeleted:Lorg/apache/poi/util/BitField;

.field private static final dataLabelPlacement:Lorg/apache/poi/util/BitField;

.field private static final generated:Lorg/apache/poi/util/BitField;

.field private static final rotation:Lorg/apache/poi/util/BitField;

.field private static final showBubbleSizes:Lorg/apache/poi/util/BitField;

.field private static final showCategoryLabelAsPercentage:Lorg/apache/poi/util/BitField;

.field private static final showKey:Lorg/apache/poi/util/BitField;

.field private static final showLabel:Lorg/apache/poi/util/BitField;

.field private static final showValue:Lorg/apache/poi/util/BitField;

.field private static final showValueAsPercentage:Lorg/apache/poi/util/BitField;

.field public static final sid:S = 0x1025s

.field private static final vertical:Lorg/apache/poi/util/BitField;


# instance fields
.field private field_10_indexOfColorValue:S

.field private field_11_options2:S

.field private field_12_textRotation:S

.field private field_1_horizontalAlignment:B

.field private field_2_verticalAlignment:B

.field private field_3_displayMode:S

.field private field_4_rgbColor:I

.field private field_5_x:I

.field private field_6_y:I

.field private field_7_width:I

.field private field_8_height:I

.field private field_9_options1:S


# direct methods
.method static constructor <clinit>()V
    .locals 1

    .line 33
    const/16 v0, 0xf

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->dataLabelPlacement:Lorg/apache/poi/util/BitField;

    .line 34
    const/4 v0, 0x1

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoColor:Lorg/apache/poi/util/BitField;

    .line 35
    const/4 v0, 0x2

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showKey:Lorg/apache/poi/util/BitField;

    .line 36
    const/4 v0, 0x4

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValue:Lorg/apache/poi/util/BitField;

    .line 37
    const/16 v0, 0x8

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->vertical:Lorg/apache/poi/util/BitField;

    .line 38
    const/16 v0, 0x10

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoGeneratedText:Lorg/apache/poi/util/BitField;

    .line 39
    const/16 v0, 0x20

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->generated:Lorg/apache/poi/util/BitField;

    .line 40
    const/16 v0, 0x40

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoLabelDeleted:Lorg/apache/poi/util/BitField;

    .line 41
    const/16 v0, 0x80

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoBackground:Lorg/apache/poi/util/BitField;

    .line 42
    const/16 v0, 0x700

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->rotation:Lorg/apache/poi/util/BitField;

    .line 44
    const/16 v0, 0x800

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showCategoryLabelAsPercentage:Lorg/apache/poi/util/BitField;

    .line 45
    const/16 v0, 0x1000

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValueAsPercentage:Lorg/apache/poi/util/BitField;

    .line 46
    const/16 v0, 0x2000

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showBubbleSizes:Lorg/apache/poi/util/BitField;

    .line 47
    const/16 v0, 0x4000

    invoke-static {v0}, Lorg/apache/poi/util/BitFieldFactory;->getInstance(I)Lorg/apache/poi/util/BitField;

    move-result-object v0

    sput-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showLabel:Lorg/apache/poi/util/BitField;

    return-void
.end method

.method public constructor <init>()V
    .locals 0

    .line 90
    invoke-direct {p0}, Lorg/apache/poi/hssf/record/StandardRecord;-><init>()V

    .line 92
    return-void
.end method

.method public constructor <init>(Lorg/apache/poi/hssf/record/RecordInputStream;)V
    .locals 1
    .param p1, "in"    # Lorg/apache/poi/hssf/record/RecordInputStream;

    .line 95
    invoke-direct {p0}, Lorg/apache/poi/hssf/record/StandardRecord;-><init>()V

    .line 96
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readByte()B

    move-result v0

    iput-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    .line 97
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readByte()B

    move-result v0

    iput-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    .line 98
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    .line 99
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    .line 100
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    .line 101
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    .line 102
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    .line 103
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readInt()I

    move-result v0

    iput v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    .line 104
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 105
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    .line 106
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    .line 107
    invoke-virtual {p1}, Lorg/apache/poi/hssf/record/RecordInputStream;->readShort()S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    .line 108
    return-void
.end method


# virtual methods
.method public clone()Ljava/lang/Object;
    .locals 2

    .line 207
    new-instance v0, Lorg/apache/poi/hssf/record/chart/TextRecord;

    invoke-direct {v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;-><init>()V

    .line 209
    .local v0, "rec":Lorg/apache/poi/hssf/record/chart/TextRecord;
    iget-byte v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    iput-byte v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    .line 210
    iget-byte v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    iput-byte v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    .line 211
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    .line 212
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    .line 213
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    .line 214
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    .line 215
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    .line 216
    iget v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    iput v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    .line 217
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 218
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    .line 219
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    .line 220
    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    iput-short v1, v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    .line 221
    return-object v0
.end method

.method public getDataLabelPlacement()S
    .locals 2

    .line 703
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->dataLabelPlacement:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->getShortValue(S)S

    move-result v0

    return v0
.end method

.method protected getDataSize()I
    .locals 1

    .line 198
    const/16 v0, 0x20

    return v0
.end method

.method public getDisplayMode()S
    .locals 1

    .line 294
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    return v0
.end method

.method public getHeight()I
    .locals 1

    .line 379
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    return v0
.end method

.method public getHorizontalAlignment()B
    .locals 1

    .line 238
    iget-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    return v0
.end method

.method public getIndexOfColorValue()S
    .locals 1

    .line 411
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    return v0
.end method

.method public getOptions1()S
    .locals 1

    .line 395
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    return v0
.end method

.method public getOptions2()S
    .locals 1

    .line 427
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    return v0
.end method

.method public getRgbColor()I
    .locals 1

    .line 315
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    return v0
.end method

.method public getRotation()S
    .locals 2

    .line 613
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->rotation:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->getShortValue(S)S

    move-result v0

    return v0
.end method

.method public getSid()S
    .locals 1

    .line 203
    const/16 v0, 0x1025

    return v0
.end method

.method public getTextRotation()S
    .locals 1

    .line 443
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    return v0
.end method

.method public getVerticalAlignment()B
    .locals 1

    .line 267
    iget-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    return v0
.end method

.method public getWidth()I
    .locals 1

    .line 363
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    return v0
.end method

.method public getX()I
    .locals 1

    .line 331
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    return v0
.end method

.method public getY()I
    .locals 1

    .line 347
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    return v0
.end method

.method public isAutoBackground()Z
    .locals 2

    .line 595
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoBackground:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isAutoColor()Z
    .locals 2

    .line 469
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoColor:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isAutoGeneratedText()Z
    .locals 2

    .line 541
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoGeneratedText:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isAutoLabelDeleted()Z
    .locals 2

    .line 577
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoLabelDeleted:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isGenerated()Z
    .locals 2

    .line 559
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->generated:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowBubbleSizes()Z
    .locals 2

    .line 667
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showBubbleSizes:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowCategoryLabelAsPercentage()Z
    .locals 2

    .line 631
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showCategoryLabelAsPercentage:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowKey()Z
    .locals 2

    .line 487
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showKey:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowLabel()Z
    .locals 2

    .line 685
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showLabel:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowValue()Z
    .locals 2

    .line 505
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValue:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isShowValueAsPercentage()Z
    .locals 2

    .line 649
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValueAsPercentage:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public isVertical()Z
    .locals 2

    .line 523
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->vertical:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1}, Lorg/apache/poi/util/BitField;->isSet(I)Z

    move-result v0

    return v0
.end method

.method public serialize(Lorg/apache/poi/util/LittleEndianOutput;)V
    .locals 1
    .param p1, "out"    # Lorg/apache/poi/util/LittleEndianOutput;

    .line 183
    iget-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeByte(I)V

    .line 184
    iget-byte v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeByte(I)V

    .line 185
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 186
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 187
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 188
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 189
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 190
    iget v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeInt(I)V

    .line 191
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 192
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 193
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 194
    iget-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    invoke-interface {p1, v0}, Lorg/apache/poi/util/LittleEndianOutput;->writeShort(I)V

    .line 195
    return-void
.end method

.method public setAutoBackground(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 586
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoBackground:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 587
    return-void
.end method

.method public setAutoColor(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 460
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoColor:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 461
    return-void
.end method

.method public setAutoGeneratedText(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 532
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoGeneratedText:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 533
    return-void
.end method

.method public setAutoLabelDeleted(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 568
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->autoLabelDeleted:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 569
    return-void
.end method

.method public setDataLabelPlacement(S)V
    .locals 2
    .param p1, "value"    # S

    .line 694
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->dataLabelPlacement:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortValue(SS)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    .line 695
    return-void
.end method

.method public setDisplayMode(S)V
    .locals 0
    .param p1, "field_3_displayMode"    # S

    .line 307
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_3_displayMode:S

    .line 308
    return-void
.end method

.method public setGenerated(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 550
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->generated:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 551
    return-void
.end method

.method public setHeight(I)V
    .locals 0
    .param p1, "field_8_height"    # I

    .line 387
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_8_height:I

    .line 388
    return-void
.end method

.method public setHorizontalAlignment(B)V
    .locals 0
    .param p1, "field_1_horizontalAlignment"    # B

    .line 253
    iput-byte p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_1_horizontalAlignment:B

    .line 254
    return-void
.end method

.method public setIndexOfColorValue(S)V
    .locals 0
    .param p1, "field_10_indexOfColorValue"    # S

    .line 419
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_10_indexOfColorValue:S

    .line 420
    return-void
.end method

.method public setOptions1(S)V
    .locals 0
    .param p1, "field_9_options1"    # S

    .line 403
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 404
    return-void
.end method

.method public setOptions2(S)V
    .locals 0
    .param p1, "field_11_options2"    # S

    .line 435
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_11_options2:S

    .line 436
    return-void
.end method

.method public setRgbColor(I)V
    .locals 0
    .param p1, "field_4_rgbColor"    # I

    .line 323
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_4_rgbColor:I

    .line 324
    return-void
.end method

.method public setRotation(S)V
    .locals 2
    .param p1, "value"    # S

    .line 604
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->rotation:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortValue(SS)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 605
    return-void
.end method

.method public setShowBubbleSizes(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 658
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showBubbleSizes:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 659
    return-void
.end method

.method public setShowCategoryLabelAsPercentage(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 622
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showCategoryLabelAsPercentage:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 623
    return-void
.end method

.method public setShowKey(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 478
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showKey:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 479
    return-void
.end method

.method public setShowLabel(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 676
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showLabel:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 677
    return-void
.end method

.method public setShowValue(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 496
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValue:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 497
    return-void
.end method

.method public setShowValueAsPercentage(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 640
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->showValueAsPercentage:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 641
    return-void
.end method

.method public setTextRotation(S)V
    .locals 0
    .param p1, "field_12_textRotation"    # S

    .line 451
    iput-short p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_12_textRotation:S

    .line 452
    return-void
.end method

.method public setVertical(Z)V
    .locals 2
    .param p1, "value"    # Z

    .line 514
    sget-object v0, Lorg/apache/poi/hssf/record/chart/TextRecord;->vertical:Lorg/apache/poi/util/BitField;

    iget-short v1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    invoke-virtual {v0, v1, p1}, Lorg/apache/poi/util/BitField;->setShortBoolean(SZ)S

    move-result v0

    iput-short v0, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_9_options1:S

    .line 515
    return-void
.end method

.method public setVerticalAlignment(B)V
    .locals 0
    .param p1, "field_2_verticalAlignment"    # B

    .line 282
    iput-byte p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_2_verticalAlignment:B

    .line 283
    return-void
.end method

.method public setWidth(I)V
    .locals 0
    .param p1, "field_7_width"    # I

    .line 371
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_7_width:I

    .line 372
    return-void
.end method

.method public setX(I)V
    .locals 0
    .param p1, "field_5_x"    # I

    .line 339
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_5_x:I

    .line 340
    return-void
.end method

.method public setY(I)V
    .locals 0
    .param p1, "field_6_y"    # I

    .line 355
    iput p1, p0, Lorg/apache/poi/hssf/record/chart/TextRecord;->field_6_y:I

    .line 356
    return-void
.end method

.method public toString()Ljava/lang/String;
    .locals 8

    .line 112
    new-instance v0, Ljava/lang/StringBuffer;

    invoke-direct {v0}, Ljava/lang/StringBuffer;-><init>()V

    .line 114
    .local v0, "buffer":Ljava/lang/StringBuffer;
    const-string v1, "[TEXT]\n"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 115
    const-string v1, "    .horizontalAlignment  = "

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v1

    const-string v2, "0x"

    invoke-virtual {v1, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v1

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getHorizontalAlignment()B

    move-result v3

    invoke-static {v3}, Lorg/apache/poi/util/HexDump;->toHex(B)Ljava/lang/String;

    move-result-object v3

    invoke-virtual {v1, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v1

    const-string v3, " ("

    invoke-virtual {v1, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v1

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getHorizontalAlignment()B

    move-result v4

    invoke-virtual {v1, v4}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v1

    const-string v4, " )"

    invoke-virtual {v1, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 118
    const-string v1, "line.separator"

    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 119
    const-string v5, "    .verticalAlignment    = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getVerticalAlignment()B

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(B)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getVerticalAlignment()B

    move-result v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 122
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 123
    const-string v5, "    .displayMode          = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getDisplayMode()S

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getDisplayMode()S

    move-result v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 126
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 127
    const-string v5, "    .rgbColor             = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getRgbColor()I

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getRgbColor()I

    move-result v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 130
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 131
    const-string v5, "    .x                    = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getX()I

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getX()I

    move-result v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 134
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 135
    const-string v5, "    .y                    = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getY()I

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getY()I

    move-result v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 138
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 139
    const-string v5, "    .width                = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getWidth()I

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getWidth()I

    move-result v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 142
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 143
    const-string v5, "    .height               = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getHeight()I

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(I)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getHeight()I

    move-result v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 146
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 147
    const-string v5, "    .options1             = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getOptions1()S

    move-result v6

    invoke-static {v6}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getOptions1()S

    move-result v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 150
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 151
    const-string v5, "         .autoColor                = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isAutoColor()Z

    move-result v6

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    const/16 v6, 0xa

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 152
    const-string v5, "         .showKey                  = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowKey()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 153
    const-string v5, "         .showValue                = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowValue()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 154
    const-string v5, "         .vertical                 = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isVertical()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 155
    const-string v5, "         .autoGeneratedText        = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isAutoGeneratedText()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 156
    const-string v5, "         .generated                = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isGenerated()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 157
    const-string v5, "         .autoLabelDeleted         = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isAutoLabelDeleted()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 158
    const-string v5, "         .autoBackground           = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isAutoBackground()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 159
    const-string v5, "         .rotation                 = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getRotation()S

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 160
    const-string v5, "         .showCategoryLabelAsPercentage     = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowCategoryLabelAsPercentage()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 161
    const-string v5, "         .showValueAsPercentage     = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowValueAsPercentage()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 162
    const-string v5, "         .showBubbleSizes          = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowBubbleSizes()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 163
    const-string v5, "         .showLabel                = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->isShowLabel()Z

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Z)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 164
    const-string v5, "    .indexOfColorValue    = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getIndexOfColorValue()S

    move-result v7

    invoke-static {v7}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getIndexOfColorValue()S

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 167
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 168
    const-string v5, "    .options2             = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getOptions2()S

    move-result v7

    invoke-static {v7}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getOptions2()S

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 171
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 172
    const-string v5, "         .dataLabelPlacement       = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getDataLabelPlacement()S

    move-result v7

    invoke-virtual {v5, v7}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;

    .line 173
    const-string v5, "    .textRotation         = "

    invoke-virtual {v0, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v2

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getTextRotation()S

    move-result v5

    invoke-static {v5}, Lorg/apache/poi/util/HexDump;->toHex(S)Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v2, v5}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v2

    invoke-virtual {v2, v3}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v2

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->getTextRotation()S

    move-result v3

    invoke-virtual {v2, v3}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v2

    invoke-virtual {v2, v4}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 176
    invoke-static {v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 178
    const-string v1, "[/TEXT]\n"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    .line 179
    invoke-virtual {v0}, Ljava/lang/StringBuffer;->toString()Ljava/lang/String;

    move-result-object v1

    return-object v1
.end method
