package com.poverka.app.util

/**
 * JSON field name constants matching the original app's MyJSON enum.
 */
object MyJSON {
    const val ID = "id"
    const val LOCAL = "local"
    const val SERVICE_TYPE = "service_type"
    const val COUNTER_NUMBER = "counter_number"
    const val START_VOLUME = "start_volume"
    const val PRODUCTION_YEAR = "production_year"
    const val WATER_TEMPERATURE = "water_temperature"
    const val TEST_NAME = "test_name"
    const val MULTIPLIER = "multiplier"
    const val MEAS_NUMB = "meas_numb"
    const val REIT_NUMB = "reit_numb"
    const val TEST_PHOTO = "test_photo"
    const val ACTION = "action"
    const val REPORT = "report"
    const val DATE_TIME = "date_time"
    const val DATE_FROM_NET = "date_from_net"
    const val SLEEP_TYPE = "sleep_type"
    const val POWER_ON_OFF = "powerOnOff"
    const val FINISH = "finish"
    const val REQUEST = "request"
    const val CUR_CON = "cur_con"
    const val AVERAGE_CON = "average_con"
    const val CUR_VOLUME = "cur_volume"
    const val CUR_VERIFS = "cur_verifs"
    const val COUNT_FILE_STATUS = "count_file_status"
    const val CHARGE_BATT = "charge_batt"
    const val TEMPER = "temper"
    const val TEMPER_DEV = "temper_dev"
    const val PRESS_DEV = "press_dev"
    const val HUM_DEV = "hum_dev"
    const val DURATION = "duration"
    const val FIRST_VAL = "first_val"
    const val LAST_VAL = "last_val"
    const val CALC_ERROR = "calc_error"
    const val RESULT = "result"
    const val VER_SOFT = "ver_soft"
    const val UPDATE_SOFT = "update_soft"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val TEMPERATURE = "temperature"
    const val PRESSURE = "pressure"
    const val HUMIDITY = "humidity"
    const val TYPE_ID = "type_id"
    const val VERIF_DATE = "verif_date"
    const val PROD_DATE = "prod_date"
    const val NUMBER_TODAY = "number_today"
    const val VERIF_NUMBER = "verif_number"
    const val VERIF_TODAY = "verif_today"
    const val ONLINE = "online"
    const val DUE_DATE = "due_date"
    const val INTEGR = "integr"
    const val CONTRAST = "contrast"
    const val COEFS = "coefs"
    const val CON = "con"
    const val CORR = "corr"
    const val DATE = "date"
    const val MAX_VERIFS = "max_verifs"
    const val IMP_LITER = "imp_liter"
    const val STATION = "station"
    const val PAYMENT_ACCOUNT = "payment_account"
    const val PERSONAL_ACCOUNT = "personal_account"
}
